frontend:
  allow_origins: ["http://localhost:3000", "${FRONTEND_ORIGIN}"]

app:
  host: "0.0.0.0"
  port: 8000

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  db: ${REDIS_DB}


sam_model:
  type: "vit_l" # other values: vit_h, vit_l
  points_per_side: 16 # other values: 12, 16, 32. the lower the fastest. default 32
  prediction_iou_threshold: 0.97 # other values: at least 0.8 to 1. default 0.88
  stability_score_threshold: 0.98 # other values: at least 0.8 to 1. default 0.95
  cropping_layers: 1 # fixed. default 0
  crop_points_downscale_factor: 2 # fixed. default 1
  min_mask_region_area: 200 # not nullable. larger speed up by ignoring smaller details. default 0
  box_nms_threshold: 0.5 # Stricter overlap removal (default: 0.7)
  crop_nms_threshold: 0.5 # Stricter crop overlap removal (default: 0.7)
  crop_overlap_ratio: 0.25 # Less crop overlap (default: 0.34)

sieve_dimensions: # defaults, can be changed per request from user interface
  width_cm: 1.5
  height_cm: 3.0

inference:
  interval_seconds: 60

camera_settings:
  pixels_per_cm: 67 # ruler of 20cm has 585 px
  # capture_interval_seconds: 3

paths:
  raw_image_path: "assets/raw_images/" # Directory to save captured images from camera.
  sam_output_path: "assets/sam_output_images/" # masks generated by sam
  sam_checkpoint_vit_b: "assets/checkpoints/sam_vit_b_01ec64.pth" # basic sam checkpoint
  sam_checkpoint_vit_l: "assets/checkpoints/sam_vit_l_0b3195.pth" # large sam checkpoint
  sam_checkpoint_vit_h: "assets/checkpoints/sam_vit_h_4b8939.pth" # huge sam checkpoint
